### ISSUE TITLE
Handle UnauthorizedAccessException related to running VA As Administrator

### ISSUE THREAD

**Issue by ACyprus** [alterNERDtive/VoiceAttack-profiles#138]
When running VA "As Administrator", `RatAttack-cli.exe` will return the following error when attempting to pipe through a RATSIGNAL:

`Unhandled Exception: System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.NamedPipeClientStream.Connect(Int32 timeout)
   at RatAttack.RatAttack_cli.Main(String[] args)`

Here is the associated setting in VA:

![image](https://user-images.githubusercontent.com/9026246/169704448-edccfc9a-05e8-4727-b585-d22adb567e5c.png)

**Comment by alterNERDtive** [comment]
Possible solutions:

* Handle the exception in the cli tool. Will most likely not even be seen by the user since it’s the IRC client running it.
* Check if VA is running elevated, print a warning to the log. Doesn’t solve anything, but people shouldn’t run VA elevated.
* Make the named pipe globally accessible. Not great, but solves this issue:
  ```
  PipeSecurity pSecure = new PipeSecurity();
  pSecure.SetAccessRule(new PipeAccessRule("Everyone", PipeAccessRights.ReadWrite,
  System.Security.AccessControl.AccessControlType.Allow));
  ```
* ~~Tell people to run their IRC client / the cli tool as admin.~~ No. Just no.
