### ISSUE TITLE
Opening settings without including base profile causes a crash

### ISSUE THREAD

**Issue by stephenwilliams** [alterNERDtive/VoiceAttack-profiles#162]
Hi, 

New to voice attack. When using `customize settings` I am seeing a crash:

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at alterNERDtive.SettingsDialog..ctor(Configuration config, VoiceAttackLog log)
   at alterNERDtive.BasePlugin.<>c.<Context_Config_Dialog>b__29_0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
***VoiceAttack v1.10.3.36 - Windows 10.0.19045.0
Plugin assemblies:
alterNERDtive-base 4.5 [base.dll] (enabled) - Last call: 31 Dec 2022 11:20:00:43 VA_Invoke1
bindED Plugin v4.2.2-alterNERDtive [bindEDplugin.dll] (enabled) - Last call: 31 Dec 2022 11:19:59:38 VA_Init1
EDDI 4.0.1 [EddiVoiceAttackResponder.dll] (enabled) - Last call: 31 Dec 2022 11:19:59:38 VA_Init1
EliteAttack 8.5 [EliteAttack.dll] (enabled) - Last call: 31 Dec 2022 11:19:59:38 VA_Init1
Neutron Router - v0.1.0+ [EDNeutronRouter.dll] (enabled) - Last call: 31 Dec 2022 11:19:59:38 VA_Init1
RatAttack 6.4 [RatAttack.dll] (enabled) - Last call: 31 Dec 2022 11:19:59:38 VA_Init1
SpanshAttack 7.2.2 [SpanshAttack.dll] (enabled) - Last call: 31 Dec 2022 11:19:59:38 VA_Init1
```

**Comment by stephenwilliams** [comment]
![image](https://user-images.githubusercontent.com/724904/210150202-e82e0eb7-1ea9-4361-bdd4-0633ef15f410.png)


```
VoiceAttack settings summary (last-committed values only) Saturday, December 31, 2022 11:43 AM
Windows 10.0.19045 64 bit
Last reboot: Saturday, December 31, 2022 11:26 AM

VoiceAttack 64-bit version v1.10.3.36 (prerelease)
--------------------------------------------------
Started: Saturday, December 31, 2022 11:38 AM
Running as an administrator: Yes
Compact mode enabled: No
Dark mode enabled: Yes
Always on top: No
Application culture: en-US
UI culture: en-US
Command line: "C:\Program Files\VoiceAttack\VoiceAttack.exe" 


General
---------------
Launch with Windows start: Yes
Minimize to system tray: No
Show control tips: Yes
Check for updates on startup: Yes
Include betas: True
Start minimized: No
Auto profile switching enabled: Yes
Minimize on close: No
Enable plugin support: Yes
Plugin assemblies:
alterNERDtive-base 4.5 [base.dll] (enabled) - Last call: 31 Dec 2022 11:38:53:72 VA_Invoke1
bindED Plugin v4.2.2-alterNERDtive [bindEDplugin.dll] (enabled) - Last call: 31 Dec 2022 11:38:52:66 VA_Init1
EDDI 4.0.1 [EddiVoiceAttackResponder.dll] (enabled) - Last call: 31 Dec 2022 11:38:52:66 VA_Init1
EliteAttack 8.5 [EliteAttack.dll] (enabled) - Last call: 31 Dec 2022 11:38:52:66 VA_Init1
Neutron Router - v0.1.0+ [EDNeutronRouter.dll] (enabled) - Last call: 31 Dec 2022 11:38:52:66 VA_Init1
RatAttack 6.4 [RatAttack.dll] (enabled) - Last call: 31 Dec 2022 11:38:52:66 VA_Init1
SpanshAttack 7.2.2 [SpanshAttack.dll] (enabled) - Last call: 31 Dec 2022 11:38:52:66 VA_Init1
Show tips at startup: No
Disable F1 help: No
Using 'Load Profile on Startup': No
Using 'Global Profiles': No
Keyboard Display Layout: System Default - English (United States)
User-defined sounds folder set: No
User-defined apps folder set: No

Joystick services available: Yes
Joystick polling frequency: 30
Joystick 1 Assigned: No
Joystick 2 Assigned: No
Joystick 3 Assigned: No
Joystick 4 Assigned: No

Recognition
---------------
Speech Engine: System Default (Microsoft Speech Recognizer 8.0 for Windows (English - US))
Speech disabled: No
Speech recording device muted: No
Windows speech recording device: Default - Microphone (11- SteelSeries Arctis 1 Wireless)
Recognized speech delay: 0
Unrecognized speech delay: 250
Command weight: 50
Minimum confidence: 0
Show confidence level: No
Minimum unrecognized confidence level: 50
Disable adaptive recognition: No
Disable acoustic echo cancellation: Yes
Reject pending speech: No
Using repeat command phrases: No
Using recognition prefix exclusions: Yes

Audio
---------------
Audio type: Integrated Components
Notification sounds: Yes
Fade stopped audio: Yes
Override default playback device: Do not override (use Windows Default Playback Device)
Override default text-to-speech device: Do not override (use Windows Default Playback Device)
Audio cache size: 32
Feature on sound: Default
Feature off sound: Default
Stop commands sound: Default
Sound file volume offset: 100
TTS volume offset: 100
Set Windows default multimedia audio playback device on startup: No  (Speakers (11- SteelSeries Arctis 1 Wireless))
Set Windows default communications audio playback device on startup: No  (Speakers (11- SteelSeries Arctis 1 Wireless))
Set Windows default multimedia audio recording device on startup: No  (Microphone (11- SteelSeries Arctis 1 Wireless))
Set Windows default communications audio recording device on startup: No  (Microphone (11- SteelSeries Arctis 1 Wireless))

Hotkeys
---------------
Recognition global hotkey: Toggle Left Alt+F2
Mouse click recognition: None
Joystick button recognition: Disabled
Stop all commands hotkey: Disabled
Keyboard shortcut double tap threshold: 300
Keyboard shortcut long press threshold: 700
Mouse button shortcut double tap threshold: 300
Mouse button long press threshold: 700
Joystick button shortcut double tap threshold: 300
Joystick button long press threshold: 700

System/Advanced
---------------
VoiceAttack data directory valid: Yes
Bypass mouse targeting: No
Single TTS instance: No
Cancel blocked commands: Yes
Show third-party app warnings: Yes
Stop running commands when editing: No
Allow command segment info for composite commands: No
Upon import, profiles will have, 'Block potentially harmful profile actions' selected: No
Enable log quiet mode: No
Run VoiceAttack as an administrator: No
Disable prefetch audio: No
Preserve prefetched audio on profile change: No
Speech engine type selected: Use Built-In SAPI Speech Engines (Recommended)
TTS type selected: Use Built-In SAPI Text-To-Speech Synthesizers
Enable sleep mode: No
Prevent speech engine from changing microphone volume: No

Additional Info
---------------
Speech engines installed:
Microsoft Speech Recognizer 8.0 for Windows (English - US)

Enabled playback devices:
Headphones (Oculus Virtual Audio Device) 
SAMSUNG (NVIDIA High Definition Audio) 
Speakers (11- SteelSeries Arctis 1 Wireless) [Default] [Default Communications]
Speakers (Realtek High Definition Audio) 

Enabled recording devices:
Headset Microphone (Oculus Virtual Audio Device) 
Microphone (EpocCam Camera Audio) 
Microphone (Virtual Desktop Audio) 
Microphone (Blue Snowball ) 
Microphone (11- SteelSeries Arctis 1 Wireless) [Default] [Default Communications]

Active joystick devices:
Saitek Pro Flight X-56 Rhino Stick
Saitek Pro Flight X-56 Rhino Throttle

Screen: DISPLAY1 1920 x 1080, Scaling 125%  - Primary
```

**Comment by alterNERDtive** [comment]
Weird. Good old “worksforme™”.

Does it also crash when you change a setting directly via voice command?

**Comment by stephenwilliams** [comment]
It did not crash. 

![image](https://user-images.githubusercontent.com/724904/210162577-076b7317-dad0-4e7c-bbee-5f6747dfbebd.png)

**Comment by alterNERDtive** [comment]
The “not set” in there indicates that you haven’t followed the [installation instructions](https://alternerdtive.github.io/VoiceAttack-profiles/installing/) correctly.

**Comment by stephenwilliams** [comment]
@alterNERDtive Yeah, I had my friend reinstall and use the example profile instead of option 1 and it started working
